# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- runspaces

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: 'Invoke Pester unit and code coverage testing'
  inputs:
    filePath: 'Invoke-PesterTests.ps1'
    pwsh: false

- task: PublishTestResults@2
  displayName: 'Publish NUnit test results'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/pester_test_*.xml'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish JaCoCo code coverage results'
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/pester_coverage_*.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)'
    codeCoverageTool: 'JaCoCo'
    failIfCoverageEmpty: true